### ISSUE TITLE
提供相关文档，流程图，接口文档

### ISSUE THREAD

**Issue by ejbiva1** [ejbiva1/P2a3rsk2i3n4g2H1u2bx#1]

**Comment by jayson666** [comment]
![v2](https://cloud.githubusercontent.com/assets/24238597/20698562/d026a79a-b63c-11e6-9965-55971522ed92.jpg)

**Comment by jayson666** [comment]
[宝驾车场缴费接口标准v1.1.docx](https://github.com/ejbiva1/P2a3rsk2i3n4g2H1u2bx/files/650761/v1.1.docx)

**Comment by jayson666** [comment]
[玩转停车-功能清单.xlsx](https://github.com/ejbiva1/P2a3rsk2i3n4g2H1u2bx/files/670296/-.xlsx)

**Comment by ejbiva1** [comment]
[玩转停车 2.0方案 v1.01.docx](https://github.com/ejbiva1/P2a3rsk2i3n4g2H1u2bx/files/697853/2.0.v1.01.docx)

**Comment by ejbiva1** [comment]
![image](https://cloud.githubusercontent.com/assets/5304458/21913700/f84e2b04-d968-11e6-8ebc-10ebfccb92ff.png)
